source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'KxProgressHUD' do

  use_frameworks!

  pod 'KxProgressHUD', :path => '../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end